name: nutriplato
description: Aprende a crear tu plato del Bien Comer.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  introduction_screen: ^3.1.8
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - img/
    - img/animal/
    - img/cereales/
    - img/fruits/
    - img/leguminosas/
    - img/vegetables/
