name: nutriplato
description: Aprende a crear tu plato del Bien Comer.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - img/
    - img/animal/
    - img/cereales/
    - img/fruits/
    - img/leguminosas/
    - img/vegetables/
