name: nutriplato
description: Aprende a crear tu plato del Bien Comer y cuidarte en el dia a dia.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  android_intent_plus: ^4.0.1
  circular_countdown_timer: ^0.2.3
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.4.0
  icons_plus: ^4.0.0
  introduction_screen: ^3.1.8
  provider: ^6.0.5
  random_avatar: ^0.0.8
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.1.1
  showcaseview: ^2.0.3
  social_share: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "lib/data/img/logo_nutriplato.png"

flutter:
  uses-material-design: true
  assets:
    - lib/data/img/
    - lib/data/img/porciones_mano/
    - lib/data/img/animal/
    - lib/data/img/cereales/
    - lib/data/img/fruits/
    - lib/data/img/leguminosas/
    - lib/data/img/vegetables/
